name: Docker Image CI

on:
  [workflow_dispatch]

jobs:
    pubish_images:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build image
      run: docker build ./web/ -t /genjijy/pixily:latest
    - name: Build image to dockerhub
      run: docker push /genjijy/pixily:latest
