name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: docker login
      run: docker login -u genjijy -p ${{ secrets.DOCKER_HUB_TOKEN }}
    - name: Build the Docker image
      run: docker build ./web/ -t genjijy/pixily:latest
    - name: Push image to Docker Hub
      run: docker push genjijy/pixily:latest
#
